#!/usr/bin/env bash
#
# gen_peer_cone_filters.sh
#
# Runs cone_query.py against every peer listed in a peers config file
# that has a registered IRR customer-cone as-set, and emits a
# ready-to-paste `database.saved-filters` block for Akvorado's config.
#
# Peers with NO registered as-set aren't worth listing -- there's
# nothing in IRR to expand for them. Filter their bare ASN directly in
# Akvorado instead (e.g. `DstAS = 12345`).
#
# Usage:
#   cp peers.example.conf peers.conf   # then edit peers.conf with your own peers
#   ./gen_peer_cone_filters.sh > saved-filters-snippet.yaml
#   ./gen_peer_cone_filters.sh -v -w 16 > saved-filters-snippet.yaml   # verbose, 16 workers
#   ./gen_peer_cone_filters.sh -f /path/to/other-peers.conf > out.yaml
#
# Flags:
#   -f FILE       peers config file (default: peers.conf next to this script)
#   -v            live per-object progress from cone_query.py (depth,
#                 object, host, hit/miss, timing) -- useful for the
#                 larger trees so you can see it working
#   -w WORKERS    max concurrent whois connections per peer (default: 8)
#
# peers.conf format: one peer per line, `name|as-set|extra-hosts`.
# See peers.example.conf for details and examples. peers.conf is meant
# to be private to your deployment -- it's your own peer list -- so
# don't commit it if you're working in a shared/public repo clone.
#
# Requires cone_query.py (from the a-lab repo, threaded version) to be
# on PATH or in the same directory as this script.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

VERBOSE=0
WORKERS=8
PEERS_FILE="$SCRIPT_DIR/peers.conf"

usage() {
    echo "Usage: $0 [-f PEERS_FILE] [-v] [-w WORKERS]" >&2
    echo "  -f PEERS_FILE  peers config file (default: $SCRIPT_DIR/peers.conf)" >&2
    echo "  -v             pass --verbose through to cone_query.py (live per-object progress)" >&2
    echo "  -w WORKERS     max concurrent whois connections per peer (default: 8)" >&2
    exit 1
}

while getopts "f:vw:h" opt; do
    case "$opt" in
        f) PEERS_FILE="$OPTARG" ;;
        v) VERBOSE=1 ;;
        w) WORKERS="$OPTARG" ;;
        h) usage ;;
        *) usage ;;
    esac
done

if [[ ! -f "$PEERS_FILE" ]]; then
    echo "error: peers file not found: $PEERS_FILE" >&2
    echo "" >&2
    echo "Copy the example and fill in your own peers:" >&2
    echo "    cp $SCRIPT_DIR/peers.example.conf $SCRIPT_DIR/peers.conf" >&2
    echo "    \$EDITOR $SCRIPT_DIR/peers.conf" >&2
    echo "" >&2
    echo "Or point at a specific file with -f:" >&2
    echo "    $0 -f /path/to/your-peers.conf" >&2
    exit 1
fi

CONE_QUERY="${CONE_QUERY:-$SCRIPT_DIR/cone_query.py}"

if [[ ! -x "$CONE_QUERY" ]]; then
    if command -v cone_query.py >/dev/null 2>&1; then
        CONE_QUERY="cone_query.py"
    else
        echo "error: cone_query.py not found next to this script or on PATH" >&2
        echo "       set CONE_QUERY=/path/to/cone_query.py to override" >&2
        exit 1
    fi
fi

# cone_query.py's --hosts flag REPLACES its built-in default host list
# (radb, afrinic, ntt.net) rather than adding to it -- so we build the
# full combined list here ourselves for every peer, to keep the
# multi-registry fallback behavior intact even when a peer's as-set
# needs one extra, non-default registry checked too.
DEFAULT_HOSTS="whois.radb.net,whois.afrinic.net,rr.ntt.net"

echo "# Generated by gen_peer_cone_filters.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "# Source: $PEERS_FILE"
echo "# Paste this under database.saved-filters in your Akvorado config."
echo "database:"
echo "  saved-filters:"

peer_count=0
while IFS='|' read -r name asset extra_hosts || [[ -n "$name" ]]; do
    # skip blank lines and comments
    [[ -z "$name" || "$name" =~ ^[[:space:]]*# ]] && continue

    peer_count=$((peer_count + 1))

    if [[ -n "$extra_hosts" ]]; then
        hosts="${DEFAULT_HOSTS},${extra_hosts}"
    else
        hosts="$DEFAULT_HOSTS"
    fi

    cq_args=(--hosts "$hosts" --both --workers "$WORKERS")
    [[ "$VERBOSE" -eq 1 ]] && cq_args+=(--verbose)

    echo "" >&2
    echo "==> $name ($asset) via $hosts, workers=$WORKERS" >&2

    # No stderr redirect here on purpose: with --verbose, cone_query.py's
    # per-object progress needs to stream straight to the terminal live,
    # not get buffered into a file we only look at after the fact. Only
    # stdout (the final filter clause) is captured.
    if ! clause=$("$CONE_QUERY" "${cq_args[@]}" "$asset"); then
        echo "  warning: failed to resolve $name -- see error above" >&2
        continue
    fi

    # Akvorado saved-filters entries need a description + the clause itself.
    printf '    - description: "Peer cone: %s (%s)"\n' "$name" "$asset"
    printf '      content: "%s"\n' "$clause"
done < "$PEERS_FILE"

if [[ "$peer_count" -eq 0 ]]; then
    echo "" >&2
    echo "warning: no peers found in $PEERS_FILE (only comments/blank lines?)" >&2
    exit 1
fi

echo "" >&2
echo "Done. Review the YAML above before merging -- as-set sizes and" >&2
echo "membership change over time, so re-run periodically (e.g. weekly cron)" >&2
echo "and diff against what's currently in your config." >&2
